/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IBlackScholes {
    function exp(int256 x) external view returns (uint256);

    function ln(uint256 x) external view returns (int256);

    function sqrt(uint256 x) external view returns (uint256);

    function normCdf(int256 x) external view returns (uint256);

    function normPdf(int256 x) external view returns (uint256);

    function price(uint256 s, uint256 k, uint256 t, uint256 sigma, int256 r, bool is_call) external view returns (uint256);

    function quote(uint256 s, uint256 k, uint256 t, uint256 sigma, int256 r, bool is_call) external view returns (uint256, int256, uint256, uint256, int256);

    function cappedCall(uint256 s, uint256 k, uint256 cap, uint256 t, uint256 sigma, int256 r) external view returns (uint256, int256, int256);

    function impliedVol(uint256 target, uint256 s, uint256 k, uint256 t, int256 r, bool is_call, uint256 lo, uint256 hi) external view returns (uint256, uint8);

    function ewmaUpdate(uint256 var_prev, uint256 p_prev, uint256 p_now, uint256 dt_seconds, uint256 lambda_per_day) external view returns (uint256);

    function markPortfolio(uint256 s, int256 r, uint256 sigma, uint256 cap_mult, uint256[] memory k, uint256[] memory t, bool[] memory is_call, uint256[] memory oi) external view returns (uint256, int256);

    error OutOfDomain(uint8);

    error NoConvergence(uint8);

    error LengthMismatch();

    error Overflow();
}
