"""Emit konstanta Rust & Solidity (WAD integer) dari wad_emul.py — hindari transkripsi manual.
Pakai: python3 gen_constants.py <out_rust> <out_sol>"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from wad_emul import EXP2_TABLE, A, B, C, D, P, Q, SQRPI, INV_SQRT2, THRESH, INV_SQRT_2PI, WAD, W
def limbs(v):
    return ", ".join(str((v >> (64 * i)) & ((1 << 64) - 1)) + "u64" for i in range(4))
out = []
out.append("// GENERATED by tools/reference/gen_constants.py — JANGAN diedit manual.")
out.append("// Tabel PRBMath Common.exp2: C_j = round(2^(2^-(j+1)) * 2^64), j = 0..63 (format 64.64).")
out.append("pub const EXP2_TABLE: [u128; 64] = [")
for j in range(0, 64, 2):
    out.append(f"    0x{EXP2_TABLE[j]:X}, 0x{EXP2_TABLE[j+1]:X},")
out.append("];")
def arr(name, vals):
    out.append(f"pub const {name}: [i128; {len(vals)}] = [{', '.join(str(v) for v in vals)}];")
out.append("// Koefisien Cody (SPECFUN calerf) diskalakan WAD (1e18), dibulatkan ke integer terdekat.")
arr("CODY_A", A); arr("CODY_B", B); arr("CODY_C", C); arr("CODY_D", D); arr("CODY_P", P); arr("CODY_Q", Q)
out.append(f"pub const SQRPI: i128 = {SQRPI}; // 1/sqrt(pi)")
out.append(f"pub const INV_SQRT2: i128 = {INV_SQRT2}; // 1/sqrt(2)")
out.append(f"pub const INV_SQRT_2PI: i128 = {INV_SQRT_2PI}; // 1/sqrt(2*pi)")
out.append(f"pub const CODY_THRESH: i128 = {THRESH}; // 0.46875")
out.append("pub const TWO_PI: i128 = %d; // 2*pi" % W("6.283185307179586476"))
out.append(f"// limbs U256 untuk 1e36: [{limbs(WAD*WAD)}]")
import sys
out_rs = sys.argv[1] if len(sys.argv) > 1 else "constants_gen.rs"
open(out_rs, "w").write("\n".join(out) + "\n")

# ---- Solidity: library konstanta untuk BlackScholesSol (kontrol) ----
def sol_arr(name, vals, ty="int256"):
    return "\n".join(f"    {ty} internal constant {name}{k} = {v};" for k, v in enumerate(vals))
sol = ["// SPDX-License-Identifier: MIT",
       "// GENERATED by tools/reference/gen_constants.py — JANGAN diedit manual.",
       "pragma solidity ^0.8.24;",
       "", "/// @notice Konstanta WAD identik dengan crate bs-math (Rust).", "library BsConstants {",
       sol_arr("A", A), sol_arr("B", B), sol_arr("C", C), sol_arr("D", D), sol_arr("P", P), sol_arr("Q", Q),
       f"    int256 internal constant SQRPI = {SQRPI};",
       f"    int256 internal constant INV_SQRT2 = {INV_SQRT2};",
       f"    int256 internal constant INV_SQRT_2PI = {INV_SQRT_2PI};",
       f"    int256 internal constant CODY_THRESH = {THRESH};",
       f"    int256 internal constant TWO_PI = {W('6.283185307179586476')};",
       "    int256 internal constant EXP_MAX_INPUT = 133084258667509499440;",
       "    int256 internal constant EXP_MIN_THRESHOLD = -41446531673892822322;",
       "    int256 internal constant S_MIN = 1e12;",
       "    int256 internal constant S_MAX = 1e30;",
       "    int256 internal constant T_MIN = 1902587519025;",
       "    int256 internal constant T_MAX = 1e18;",
       "    int256 internal constant SIGMA_MIN = 1e16;",
       "    int256 internal constant SIGMA_MAX = 5e18;",
       "    int256 internal constant R_ABS_MAX = 1e18;",
       "}"]
out_sol = sys.argv[2] if len(sys.argv) > 2 else "BsConstants.sol"
open(out_sol, "w").write("\n".join(sol) + "\n")
print(f"wrote {out_rs} dan {out_sol}")
