"""Emit vektor uji (WAD integer eksak dari wad_emul.py + referensi float) sebagai Rust & Solidity.
Pakai: python3 gen_vectors.py <out_rust> <out_sol>"""
import math, sys
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from wad_emul import *
from bs_numbers import bs

out_rs, out_sol = sys.argv[1], sys.argv[2]
W_ = lambda f: int(round(f * WAD))

exp_v = [(W_(x), exp_wad(W_(x))) for x in [-41.4, -40, -30, -20, -10, -5, -2, -1, -0.5, -0.1, -1e-6, 0, 1e-6, 0.1, 0.5, 1, 2, 5, 10, 20, 30, 40]]
ln_v  = [(W_(x), ln_wad(W_(x))) for x in [1e-12, 1e-9, 1e-6, 1e-3, 0.1, 0.5, 0.9, 0.95, 0.999, 1, 1.001, 1.05, 1.1, 2, 2.718281828459045, 10, 100, 4000, 1e6, 1e12]]
sqrt_v = [(W_(x), sqrt_wad(W_(x))) for x in [0, 1e-18, 1e-12, 1e-9, 0.01, 0.25, 0.5, 1, 2, 3, 4, 100, 4000, 1e6, 1e12]]
phi_v = [(W_(x), norm_cdf_wad(W_(x))) for x in [i / 20 for i in range(-170, 171)]]  # −8.5..8.5 langkah 0.05
pdf_v = [(W_(x), norm_pdf_wad(W_(x))) for x in [i / 10 for i in range(-80, 81)]]

S = 4000.0
quote_cases = []
for K in [2600, 3000, 3800, 4000, 4200, 5200, 6000]:
    for sig in [0.1, 0.3, 0.6, 1.2, 3.0]:
        for Td in [1/24, 1, 7, 30, 365]:
            for r in [0.0, 0.05]:
                for call in [True, False]:
                    quote_cases.append((K, sig, Td, r, call))
quote_v, float_v = [], []
for (K, sig, Td, r, call) in quote_cases:
    T = Td / 365
    s_, k_, t_, sg_, r_ = W_(S), W_(K), W_(T), W_(sig), W_(r)
    p, d, g, v, th = bs_quote_wad(s_, k_, t_, sg_, r_, call)
    quote_v.append((s_, k_, t_, sg_, r_, call, p, d, g, v, th))
    ref = bs(S, K, T, sig, r, call)
    float_v.append((s_, k_, t_, sg_, r_, call, ref["price"]))
capped_v = []
for (K, sig, Td) in [(4200, .6, 7), (4000, .6, 7), (4200, .6, 30), (4000, 1.0, 30), (4000, 1.5, 30), (3000, .6, 7)]:
    T = Td / 365
    args = (W_(S), W_(K), W_(2 * K), W_(T), W_(sig), 0)
    p, d, v = capped_call_wad(*args)
    capped_v.append(args + (p, d, v))
iv_v = []
for (K, sig, call, Td) in [(4200,.6,True,7),(4000,.6,False,7),(3000,.6,False,7),(5200,.6,True,7),(2600,.6,False,7),(4200,1.2,True,7),(4200,.3,True,7),(2000,.6,False,30),(6000,.6,True,7),(4000,.1,True,365),(4000,3.0,True,1)]:
    T = Td / 365
    tgt = bs_quote_wad(W_(S), W_(K), W_(T), W_(sig), 0, call)[0]
    sg, it = implied_vol_wad(tgt, W_(S), W_(K), W_(T), 0, call)
    iv_v.append((tgt, W_(S), W_(K), W_(T), 0, call, sg, it))
ewma_v = []
var = W_(0.55**2); prices = [(4000, 0), (4020, .25), (3960, .5), (4100, 1.0), (4080, 1.5), (3900, 2.0)]
for i_ in range(1, len(prices)):
    p0, t0 = prices[i_-1]; p1, t1 = prices[i_]
    dt = int((t1 - t0) * 86400)
    nv = ewma_update_wad(var, W_(p0), W_(p1), dt, W_(0.94))
    ewma_v.append((var, W_(p0), W_(p1), dt, W_(0.94), nv)); var = nv

def rs_tuple(t):
    return "(" + ", ".join(("true" if x is True else "false") if isinstance(x, bool) else (repr(x) if isinstance(x, float) else str(x)) for x in t) + ")"
def rs_arr(name, ty, rows):
    return f"pub const {name}: &[{ty}] = &[\n" + "".join(f"    {rs_tuple(r)},\n" for r in rows) + "];\n"
rs = "// GENERATED by tools/reference/gen_vectors.py — JANGAN diedit manual.\n"
rs += rs_arr("EXP", "(i128, i128)", exp_v)
rs += rs_arr("LN", "(i128, i128)", ln_v)
rs += rs_arr("SQRT", "(u128, u128)", sqrt_v)
rs += rs_arr("PHI", "(i128, i128)", phi_v)
rs += rs_arr("PDF", "(i128, i128)", pdf_v)
rs += rs_arr("QUOTE", "(i128, i128, i128, i128, i128, bool, i128, i128, i128, i128, i128)", quote_v)
rs += rs_arr("FLOAT_PRICE", "(i128, i128, i128, i128, i128, bool, f64)", float_v)
rs += rs_arr("CAPPED", "(i128, i128, i128, i128, i128, i128, i128, i128, i128)", capped_v)
rs += rs_arr("IV", "(i128, i128, i128, i128, i128, bool, i128, u8)", iv_v)
rs += rs_arr("EWMA", "(i128, i128, i128, i128, i128, i128)", ewma_v)
open(out_rs, "w").write(rs)

# Solidity: subset (Foundry) — array literal besar mahal untuk kompilasi; ambil sampel.
def sol_rows(name, rows, fields):
    lines = [f"    function {name}() internal pure returns ({', '.join(f'{ty}[] memory' for ty,_ in fields)}) {{"]
    n = len(rows)
    for j, (ty, _) in enumerate(fields):
        lines.append(f"        {ty}[] memory v{j} = new {ty}[]({n});")
    for i_, r in enumerate(rows):
        for j, (ty, idx) in enumerate(fields):
            val = r[idx]
            val = ("true" if val else "false") if isinstance(val, bool) else str(val)
            lines.append(f"        v{j}[{i_}] = {val};")
    lines.append(f"        return ({', '.join(f'v{j}' for j in range(len(fields)))});")
    lines.append("    }")
    return "\n".join(lines)
sol = "// SPDX-License-Identifier: MIT\n// GENERATED by tools/reference/gen_vectors.py — JANGAN diedit manual.\npragma solidity ^0.8.24;\n\nlibrary VectorsGen {\n"
sol += sol_rows("expV", exp_v, [("int256", 0), ("int256", 1)]) + "\n"
sol += sol_rows("lnV", ln_v, [("int256", 0), ("int256", 1)]) + "\n"
sol += sol_rows("sqrtV", sqrt_v, [("uint256", 0), ("uint256", 1)]) + "\n"
sol += sol_rows("phiV", phi_v[::5], [("int256", 0), ("int256", 1)]) + "\n"
sol += sol_rows("quoteV", quote_v[::7], [("int256", 0), ("int256", 1), ("int256", 2), ("int256", 3), ("int256", 4), ("bool", 5), ("int256", 6), ("int256", 7), ("int256", 9)]) + "\n"
sol += "}\n"
open(out_sol, "w").write(sol)
print(f"rust: exp {len(exp_v)} ln {len(ln_v)} sqrt {len(sqrt_v)} phi {len(phi_v)} pdf {len(pdf_v)} quote {len(quote_v)} capped {len(capped_v)} iv {len(iv_v)} ewma {len(ewma_v)}")
print(f"sol: phi {len(phi_v[::5])} quote {len(quote_v[::7])}")
