[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@prb/math/=lib/prb-math/",
    "forge-std/=lib/forge-std/src/",
]
