// SPDX-License-Identifier: MIT
// GENERATED by tools/reference/gen_constants.py — JANGAN diedit manual.
pragma solidity ^0.8.24;

/// @notice Konstanta WAD identik dengan crate bs-math (Rust).
library BsConstants {
    int256 internal constant A0 = 3161123743870565600;
    int256 internal constant A1 = 113864154151050156000;
    int256 internal constant A2 = 377485237685302021000;
    int256 internal constant A3 = 3209377589138469470000;
    int256 internal constant A4 = 185777706184603153;
    int256 internal constant B0 = 23601290952344120900;
    int256 internal constant B1 = 244024637934444173000;
    int256 internal constant B2 = 1282616526077372280000;
    int256 internal constant B3 = 2844236833439170620000;
    int256 internal constant C0 = 564188496988670089;
    int256 internal constant C1 = 8883149794388375940;
    int256 internal constant C2 = 66119190637141629500;
    int256 internal constant C3 = 298635138197400131000;
    int256 internal constant C4 = 881952221241769090000;
    int256 internal constant C5 = 1712047612634070580000;
    int256 internal constant C6 = 2051078377826071470000;
    int256 internal constant C7 = 1230339354797997250000;
    int256 internal constant C8 = 21531153547;
    int256 internal constant D0 = 15744926110709834700;
    int256 internal constant D1 = 117693950891312499000;
    int256 internal constant D2 = 537181101862009858000;
    int256 internal constant D3 = 1621389574566690190000;
    int256 internal constant D4 = 3290799235733459630000;
    int256 internal constant D5 = 4362619090143247160000;
    int256 internal constant D6 = 3439367674143721640000;
    int256 internal constant D7 = 1230339354803749420000;
    int256 internal constant P0 = 305326634961232344;
    int256 internal constant P1 = 360344899949804439;
    int256 internal constant P2 = 125781726111229246;
    int256 internal constant P3 = 16083785148742277;
    int256 internal constant P4 = 658749161529838;
    int256 internal constant P5 = 16315387137302098;
    int256 internal constant Q0 = 2568520192289822420;
    int256 internal constant Q1 = 1872952849923467250;
    int256 internal constant Q2 = 527905102951428412;
    int256 internal constant Q3 = 60518341312441319;
    int256 internal constant Q4 = 2335204976268692;
    int256 internal constant SQRPI = 564189583547756287;
    int256 internal constant INV_SQRT2 = 707106781186547524;
    int256 internal constant INV_SQRT_2PI = 398942280401432678;
    int256 internal constant CODY_THRESH = 468750000000000000;
    int256 internal constant TWO_PI = 6283185307179586476;
    int256 internal constant EXP_MAX_INPUT = 133084258667509499440;
    int256 internal constant EXP_MIN_THRESHOLD = -41446531673892822322;
    int256 internal constant S_MIN = 1e12;
    int256 internal constant S_MAX = 1e30;
    int256 internal constant T_MIN = 1902587519025;
    int256 internal constant T_MAX = 1e18;
    int256 internal constant SIGMA_MIN = 1e16;
    int256 internal constant SIGMA_MAX = 5e18;
    int256 internal constant R_ABS_MAX = 1e18;
}
